-- IMDb Top-chart style titles (directors corrected vs common spreadsheet errors).
-- Skips any row whose title already exists. Run 0003_add_director_column.sql first if upgrading an old DB.
-- Posters: English Wikipedia / Wikimedia (stable URLs; avoids broken TMDB hashes).

insert into public.movies (
  title, overview, poster_url, release_year, genres, category, rating, review_text, runtime_minutes, director
)
select *
from (
  values
    (
      'The Shawshank Redemption',
      'Two imprisoned men bond over years, finding solace and eventual redemption through acts of decency.',
      'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg',
      1994,
      array['drama']::text[],
      'classic',
      9.3::numeric,
      'IMDb chart mainstay. Directed by Frank Darabont.',
      null::int,
      'Frank Darabont'
    ),
    (
      'The Godfather',
      'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
      'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg',
      1972,
      array['crime', 'drama']::text[],
      'classic',
      9.2::numeric,
      'IMDb chart mainstay. Directed by Francis Ford Coppola.',
      null::int,
      'Francis Ford Coppola'
    ),
    (
      'Schindler''s List',
      'In German-occupied Poland during World War II, industrialist Oskar Schindler saves over a thousand Jewish lives.',
      'https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg',
      1993,
      array['drama', 'crime']::text[],
      'classic',
      9.0::numeric,
      'IMDb chart mainstay. Directed by Steven Spielberg.',
      null::int,
      'Steven Spielberg'
    ),
    (
      '12 Angry Men',
      'The jury in a murder trial retires to deliberate, and one holdout tries to prevent a miscarriage of justice.',
      'https://upload.wikimedia.org/wikipedia/commons/b/b5/12_Angry_Men_%281957_film_poster%29.jpg',
      1957,
      array['crime', 'drama']::text[],
      'classic',
      9.0::numeric,
      'IMDb chart mainstay. Directed by Sidney Lumet.',
      null::int,
      'Sidney Lumet'
    ),
    (
      'The Lord of the Rings: The Return of the King',
      'Gandalf and Aragorn lead the World of Men against Sauron''s army, while Frodo reaches Mount Doom.',
      'https://upload.wikimedia.org/wikipedia/en/4/48/Lord_Rings_Return_King.jpg',
      2003,
      array['action', 'adventure', 'drama']::text[],
      'classic',
      9.0::numeric,
      'IMDb chart mainstay. Directed by Peter Jackson.',
      null::int,
      'Peter Jackson'
    ),
    (
      'The Godfather Part II',
      'Parallel stories follow young Vito Corleone''s rise and Michael''s struggle to expand the family empire.',
      'https://upload.wikimedia.org/wikipedia/en/0/03/Godfather_part_ii.jpg',
      1974,
      array['crime', 'drama']::text[],
      'classic',
      9.0::numeric,
      'IMDb chart mainstay. Directed by Francis Ford Coppola.',
      null::int,
      'Francis Ford Coppola'
    ),
    (
      'Pulp Fiction',
      'Interwoven stories of Los Angeles mobsters, small-time boxers, and a mysterious briefcase.',
      'https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg',
      1994,
      array['crime', 'drama']::text[],
      'classic',
      8.9::numeric,
      'IMDb chart mainstay. Directed by Quentin Tarantino.',
      null::int,
      'Quentin Tarantino'
    ),
    (
      'Fight Club',
      'An insomniac office worker and a soap maker build an underground fight club that spirals out of control.',
      'https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg',
      1999,
      array['drama']::text[],
      'classic',
      8.8::numeric,
      'IMDb chart mainstay. Directed by David Fincher.',
      null::int,
      'David Fincher'
    ),
    (
      'The Lord of the Rings: The Fellowship of the Ring',
      'A meek Hobbit and eight companions set out to destroy the One Ring and defeat the Dark Lord Sauron.',
      'https://upload.wikimedia.org/wikipedia/en/f/fb/Lord_Rings_Fellowship_Ring.jpg',
      2001,
      array['action', 'adventure', 'drama']::text[],
      'classic',
      8.8::numeric,
      'IMDb chart mainstay. Directed by Peter Jackson.',
      null::int,
      'Peter Jackson'
    ),
    (
      'Forrest Gump',
      'The history of the United States unfolds through the life of an Alabama man with a big heart.',
      'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg',
      1994,
      array['drama', 'romance']::text[],
      'classic',
      8.8::numeric,
      'IMDb chart mainstay. Directed by Robert Zemeckis.',
      null::int,
      'Robert Zemeckis'
    ),
    (
      'The Lord of the Rings: The Two Towers',
      'Frodo and Sam edge toward Mordor while the divided fellowship fights Saruman and Sauron''s forces.',
      'https://upload.wikimedia.org/wikipedia/en/a/a1/Lord_Rings_Two_Towers.jpg',
      2002,
      array['action', 'adventure', 'drama']::text[],
      'classic',
      8.8::numeric,
      'IMDb chart mainstay. Directed by Peter Jackson.',
      null::int,
      'Peter Jackson'
    ),
    (
      'The Good, the Bad and the Ugly',
      'Three gunslingers compete to find a fortune in buried Confederate gold amid the Civil War.',
      'https://upload.wikimedia.org/wikipedia/en/4/45/Good_the_bad_and_the_ugly_poster.jpg',
      1966,
      array['adventure', 'drama']::text[],
      'classic',
      8.8::numeric,
      'IMDb chart mainstay. Directed by Sergio Leone.',
      null::int,
      'Sergio Leone'
    ),
    (
      'Spider-Man: Across the Spider-Verse',
      'Miles Morales catapults across the Multiverse and faces a team of Spider-People protecting its existence.',
      'https://upload.wikimedia.org/wikipedia/en/b/b4/Spider-Man-_Across_the_Spider-Verse_poster.jpg',
      2023,
      array['animation', 'action', 'adventure']::text[],
      'trending',
      8.7::numeric,
      'IMDb chart mainstay. Directed by Joaquim Dos Santos, Kemp Powers, and Justin K. Thompson.',
      null::int,
      'Joaquim Dos Santos'
    ),
    (
      'Goodfellas',
      'The story of Henry Hill and his life in the mob, from small-time thief to FBI informant.',
      'https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg',
      1990,
      array['crime', 'drama']::text[],
      'classic',
      8.7::numeric,
      'IMDb chart mainstay. Directed by Martin Scorsese.',
      null::int,
      'Martin Scorsese'
    ),
    (
      'The Matrix',
      'A computer hacker learns reality is a simulation and joins a rebellion against its machine overlords.',
      'https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png',
      1999,
      array['action', 'sci-fi']::text[],
      'classic',
      8.7::numeric,
      'IMDb chart mainstay. Directed by Lana and Lilly Wachowski.',
      null::int,
      'Lana Wachowski'
    ),
    (
      'One Flew Over the Cuckoo''s Nest',
      'A rebellious patient rallies fellow inmates against a domineering nurse in a mental institution.',
      'https://upload.wikimedia.org/wikipedia/en/2/26/One_Flew_Over_the_Cuckoo%27s_Nest_poster.jpg',
      1975,
      array['drama']::text[],
      'classic',
      8.7::numeric,
      'IMDb chart mainstay. Directed by Miloš Forman.',
      null::int,
      'Miloš Forman'
    ),
    (
      'Star Wars: Episode V - The Empire Strikes Back',
      'The Rebels scatter after the Empire attacks Hoth, while Luke trains with Yoda and learns a shattering truth.',
      'https://upload.wikimedia.org/wikipedia/en/3/3f/The_Empire_Strikes_Back_%281980_film%29.jpg',
      1980,
      array['action', 'adventure', 'fantasy']::text[],
      'classic',
      8.7::numeric,
      'IMDb chart mainstay. Directed by Irvin Kershner.',
      null::int,
      'Irvin Kershner'
    ),
    (
      'Oppenheimer',
      'The story of J. Robert Oppenheimer and the Manhattan Project, and the cost of building the atomic bomb.',
      'https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg',
      2023,
      array['drama', 'thriller']::text[],
      'trending',
      8.6::numeric,
      'IMDb chart mainstay. Directed by Christopher Nolan.',
      null::int,
      'Christopher Nolan'
    ),
    (
      'Se7en',
      'Two detectives hunt a serial killer who uses the seven deadly sins as his motif.',
      'https://upload.wikimedia.org/wikipedia/en/6/68/Seven_%28movie%29_poster.jpg',
      1995,
      array['crime', 'drama', 'thriller']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by David Fincher.',
      null::int,
      'David Fincher'
    ),
    (
      'The Silence of the Lambs',
      'A young FBI trainee seeks the help of imprisoned cannibal Dr. Hannibal Lecter to catch another killer.',
      'https://upload.wikimedia.org/wikipedia/en/8/86/The_Silence_of_the_Lambs_poster.jpg',
      1991,
      array['crime', 'drama', 'thriller']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by Jonathan Demme.',
      null::int,
      'Jonathan Demme'
    ),
    (
      'Star Wars: Episode IV - A New Hope',
      'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, and two droids to save the galaxy.',
      'https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg',
      1977,
      array['action', 'adventure', 'fantasy']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by George Lucas.',
      null::int,
      'George Lucas'
    ),
    (
      'Saving Private Ryan',
      'Following the Normandy landings, U.S. soldiers go behind enemy lines to retrieve a paratrooper.',
      'https://upload.wikimedia.org/wikipedia/en/a/ac/Saving_Private_Ryan_poster.jpg',
      1998,
      array['drama']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by Steven Spielberg.',
      null::int,
      'Steven Spielberg'
    ),
    (
      'The Green Mile',
      'Death row guards witness supernatural events after an enigmatic inmate arrives at Cold Mountain Penitentiary.',
      'https://upload.wikimedia.org/wikipedia/en/e/e2/The_Green_Mile_%28movie_poster%29.jpg',
      1999,
      array['crime', 'drama', 'fantasy']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by Frank Darabont.',
      null::int,
      'Frank Darabont'
    ),
    (
      'Terminator 2: Judgment Day',
      'A reprogrammed Terminator protects John Connor from a more advanced liquid-metal assassin.',
      'https://upload.wikimedia.org/wikipedia/en/5/5e/Terminator_2-Judgment_Day.png',
      1991,
      array['action', 'sci-fi']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by James Cameron.',
      null::int,
      'James Cameron'
    ),
    (
      'Spirited Away',
      'During her family''s move to the suburbs, a sullen girl wanders into a world ruled by gods and spirits.',
      'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png',
      2001,
      array['animation', 'adventure', 'drama']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by Hayao Miyazaki.',
      null::int,
      'Hayao Miyazaki'
    ),
    (
      'City of God',
      'In the slums of Rio, two boys take different paths as one becomes a photographer and the other a drug dealer.',
      'https://upload.wikimedia.org/wikipedia/en/1/10/CidadedeDeus.jpg',
      2002,
      array['crime', 'drama']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by Fernando Meirelles.',
      null::int,
      'Fernando Meirelles'
    ),
    (
      'Life Is Beautiful',
      'A Jewish Italian bookseller uses humor and imagination to shield his son from the horrors of a concentration camp.',
      'https://upload.wikimedia.org/wikipedia/en/7/7c/Vitaebella.jpg',
      1997,
      array['comedy', 'drama', 'romance']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by Roberto Benigni.',
      null::int,
      'Roberto Benigni'
    ),
    (
      'It''s a Wonderful Life',
      'An angel shows a frustrated businessman what life would have been like if he had never existed.',
      'https://upload.wikimedia.org/wikipedia/commons/2/25/It%27s_a_Wonderful_Life_%281946_poster%29.jpeg',
      1946,
      array['drama', 'romance']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by Frank Capra.',
      null::int,
      'Frank Capra'
    ),
    (
      'Seven Samurai',
      'Farmers hire seven masterless samurai to defend their village from bandits.',
      'https://upload.wikimedia.org/wikipedia/en/c/c8/Seven_Samurai_Poster.png',
      1954,
      array['action', 'drama']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by Akira Kurosawa.',
      null::int,
      'Akira Kurosawa'
    ),
    (
      'Harakiri',
      'An aging ronin requests permission to commit ritual suicide in a lord''s courtyard, exposing hypocrisy.',
      'https://upload.wikimedia.org/wikipedia/en/f/fd/Harakiri_Poster.jpg',
      1962,
      array['action', 'drama', 'thriller']::text[],
      'classic',
      8.6::numeric,
      'IMDb chart mainstay. Directed by Masaki Kobayashi.',
      null::int,
      'Masaki Kobayashi'
    ),
    (
      'Gladiator',
      'A former Roman general seeks vengeance against the corrupt emperor who murdered his family.',
      'https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png',
      2000,
      array['action', 'adventure', 'drama']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Ridley Scott.',
      null::int,
      'Ridley Scott'
    ),
    (
      'Alien',
      'The crew of a commercial spacecraft encounters a deadly extraterrestrial organism.',
      'https://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg',
      1979,
      array['horror', 'sci-fi']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Ridley Scott.',
      null::int,
      'Ridley Scott'
    ),
    (
      'Parasite',
      'Greed and class discrimination threaten the symbiotic relationship between the wealthy Park family and the destitute Kims.',
      'https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png',
      2019,
      array['drama', 'thriller']::text[],
      'trending',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Bong Joon-ho.',
      null::int,
      'Bong Joon-ho'
    ),
    (
      'The Departed',
      'An undercover cop and a mole in the police try to identify each other while infiltrating an Irish gang.',
      'https://upload.wikimedia.org/wikipedia/en/5/50/Departed234.jpg',
      2006,
      array['crime', 'drama', 'thriller']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Martin Scorsese.',
      null::int,
      'Martin Scorsese'
    ),
    (
      'The Prestige',
      'Two stage magicians engage in competitive one-upmanship in Victorian London—with deadly consequences.',
      'https://upload.wikimedia.org/wikipedia/en/d/d2/Prestige_poster.jpg',
      2006,
      array['drama', 'thriller', 'sci-fi']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Christopher Nolan.',
      null::int,
      'Christopher Nolan'
    ),
    (
      'Whiplash',
      'A young drummer enrolls at a cut-throat music conservatory where a conductor pushes him past his limits.',
      'https://upload.wikimedia.org/wikipedia/en/0/01/Whiplash_poster.jpg',
      2014,
      array['drama']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Damien Chazelle.',
      null::int,
      'Damien Chazelle'
    ),
    (
      'Back to the Future',
      'A teen is sent 30 years into the past in a time-traveling DeLorean invented by his eccentric friend.',
      'https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg',
      1985,
      array['adventure', 'comedy', 'sci-fi']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Robert Zemeckis.',
      null::int,
      'Robert Zemeckis'
    ),
    (
      'Léon: The Professional',
      'A hitman takes in a young girl after her family is murdered, and teaches her his trade.',
      'https://upload.wikimedia.org/wikipedia/en/0/03/Leon-poster.jpg',
      1994,
      array['action', 'crime', 'drama']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Luc Besson.',
      null::int,
      'Luc Besson'
    ),
    (
      'Django Unchained',
      'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal plantation owner.',
      'https://upload.wikimedia.org/wikipedia/en/8/8b/Django_Unchained_Poster.jpg',
      2012,
      array['drama', 'crime']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Quentin Tarantino.',
      null::int,
      'Quentin Tarantino'
    ),
    (
      'The Lion King',
      'A lion prince flees his kingdom after his father''s murder, only to learn the true meaning of responsibility.',
      'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg',
      1994,
      array['animation', 'adventure', 'drama']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Roger Allers and Rob Minkoff.',
      null::int,
      'Roger Allers'
    ),
    (
      'The Usual Suspects',
      'A sole survivor recounts the twist-filled path to a deadly harbor shoot-out.',
      'https://upload.wikimedia.org/wikipedia/en/9/9c/Usual_suspects_ver1.jpg',
      1995,
      array['crime', 'drama', 'thriller']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Bryan Singer.',
      null::int,
      'Bryan Singer'
    ),
    (
      'American History X',
      'A former neo-nazi tries to prevent his younger brother from going down the same wrong path.',
      'https://upload.wikimedia.org/wikipedia/en/3/39/American_History_X_poster.png',
      1998,
      array['crime', 'drama']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Tony Kaye.',
      null::int,
      'Tony Kaye'
    ),
    (
      'Psycho',
      'A secretary on the run checks into a remote motel run by a young man dominated by his mother.',
      'https://upload.wikimedia.org/wikipedia/commons/7/76/Psycho_%281960%29_theatrical_poster_%28retouched%29.jpg',
      1960,
      array['horror', 'thriller']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Alfred Hitchcock.',
      null::int,
      'Alfred Hitchcock'
    ),
    (
      'The Pianist',
      'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto during World War II.',
      'https://upload.wikimedia.org/wikipedia/en/a/a6/The_Pianist_movie.jpg',
      2002,
      array['drama']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Roman Polanski.',
      null::int,
      'Roman Polanski'
    ),
    (
      'Casablanca',
      'A cynical expatriate struggles to decide whether to help his former lover and her fugitive husband escape.',
      'https://upload.wikimedia.org/wikipedia/commons/b/b3/CasablancaPoster-Gold.jpg',
      1942,
      array['drama', 'romance']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Michael Curtiz.',
      null::int,
      'Michael Curtiz'
    ),
    (
      'The Intouchables',
      'An unlikely friendship forms between a quadriplegic aristocrat and his exuberant caregiver from the projects.',
      'https://upload.wikimedia.org/wikipedia/en/9/93/The_Intouchables.jpg',
      2011,
      array['comedy', 'drama']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Olivier Nakache and Éric Toledano.',
      null::int,
      'Olivier Nakache'
    ),
    (
      'Grave of the Fireflies',
      'A teenage boy and his younger sister struggle to survive in Japan during the final months of World War II.',
      'https://upload.wikimedia.org/wikipedia/en/a/a5/Grave_of_the_Fireflies_Japanese_poster.jpg',
      1988,
      array['animation', 'drama']::text[],
      'classic',
      8.5::numeric,
      'IMDb chart mainstay. Directed by Isao Takahata.',
      null::int,
      'Isao Takahata'
    )
) as v (
  title, overview, poster_url, release_year, genres, category, rating, review_text, runtime_minutes, director
)
where not exists (select 1 from public.movies m where m.title = v.title);
