-- Fix broken TMDB poster URLs: point to stable Wikipedia/Wikimedia posters.
-- Safe to re-run; updates by exact title match.

update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/commons/b/b5/12_Angry_Men_%281957_film_poster%29.jpg' where title = '12 Angry Men';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg' where title = 'Alien';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/3/39/American_History_X_poster.png' where title = 'American History X';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg' where title = 'Back to the Future';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/commons/b/b3/CasablancaPoster-Gold.jpg' where title = 'Casablanca';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/10/CidadedeDeus.jpg' where title = 'City of God';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/8/8b/Django_Unchained_Poster.jpg' where title = 'Django Unchained';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/5/52/Dune_Part_Two_poster.jpeg' where title = 'Dune: Part Two';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg' where title = 'Fight Club';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg' where title = 'Forrest Gump';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png' where title = 'Gladiator';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg' where title = 'Goodfellas';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/a/a5/Grave_of_the_Fireflies_Japanese_poster.jpg' where title = 'Grave of the Fireflies';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/f/fd/Harakiri_Poster.jpg' where title = 'Harakiri';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg' where title = 'Inception';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg' where title = 'Interstellar';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/commons/2/25/It%27s_a_Wonderful_Life_%281946_poster%29.jpeg' where title = 'It''s a Wonderful Life';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/7/7c/Vitaebella.jpg' where title = 'Life Is Beautiful';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/0/03/Leon-poster.jpg' where title = 'Léon: The Professional';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/2/26/One_Flew_Over_the_Cuckoo%27s_Nest_poster.jpg' where title = 'One Flew Over the Cuckoo''s Nest';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg' where title = 'Oppenheimer';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png' where title = 'Parasite';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/commons/7/76/Psycho_%281960%29_theatrical_poster_%28retouched%29.jpg' where title = 'Psycho';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg' where title = 'Pulp Fiction';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/a/ac/Saving_Private_Ryan_poster.jpg' where title = 'Saving Private Ryan';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg' where title = 'Schindler''s List';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/6/68/Seven_%28movie%29_poster.jpg' where title = 'Se7en';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/c/c8/Seven_Samurai_Poster.png' where title = 'Seven Samurai';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/b/b4/Spider-Man-_Across_the_Spider-Verse_poster.jpg' where title = 'Spider-Man: Across the Spider-Verse';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png' where title = 'Spirited Away';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg' where title = 'Star Wars: Episode IV - A New Hope';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/3/3f/The_Empire_Strikes_Back_%281980_film%29.jpg' where title = 'Star Wars: Episode V - The Empire Strikes Back';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/5/5e/Terminator_2-Judgment_Day.png' where title = 'Terminator 2: Judgment Day';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg' where title = 'The Dark Knight';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/5/50/Departed234.jpg' where title = 'The Departed';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg' where title = 'The Godfather';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/0/03/Godfather_part_ii.jpg' where title = 'The Godfather Part II';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/4/45/Good_the_bad_and_the_ugly_poster.jpg' where title = 'The Good, the Bad and the Ugly';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/e/e2/The_Green_Mile_%28movie_poster%29.jpg' where title = 'The Green Mile';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/9/93/The_Intouchables.jpg' where title = 'The Intouchables';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg' where title = 'The Lion King';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/f/fb/Lord_Rings_Fellowship_Ring.jpg' where title = 'The Lord of the Rings: The Fellowship of the Ring';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/4/48/Lord_Rings_Return_King.jpg' where title = 'The Lord of the Rings: The Return of the King';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/a/a1/Lord_Rings_Two_Towers.jpg' where title = 'The Lord of the Rings: The Two Towers';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png' where title = 'The Matrix';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/a/a6/The_Pianist_movie.jpg' where title = 'The Pianist';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/d2/Prestige_poster.jpg' where title = 'The Prestige';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg' where title = 'The Shawshank Redemption';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/8/86/The_Silence_of_the_Lambs_poster.jpg' where title = 'The Silence of the Lambs';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/9/9c/Usual_suspects_ver1.jpg' where title = 'The Usual Suspects';
update public.movies set poster_url = 'https://upload.wikimedia.org/wikipedia/en/0/01/Whiplash_poster.jpg' where title = 'Whiplash';
